# Generated by Django 5.0.6 on 2024-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskDescription',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
