# Generated by Django 5.0.6 on 2024-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_taskmodel_taskdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='CompletedDate',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
