# Generated by Django 5.0.6 on 2024-06-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_taskmodel_completeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Status',
            field=models.CharField(default='On-Going', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskDescription',
            field=models.TextField(null=True),
        ),
    ]
